---
# XXX: Yes, this is really ugly. The ugliness here results in some easier-to-
# read per-distribution defaults in vars/main.yml
#
# See vars/main.yml for more clarity on what's happening here.
#
# Basically, we're looking for the most specific entry (distribution +
# version) in the dict to inform us of our default packages if
# `postgres_packages` is null.
#
# If no version-specific entry exists, we use the distro entry. If the distro
# entry doesn't exist, and postgresql_packages is null, then we have nothing
# but that platform wouldn't be listed as handled in our meta/main.yml file.
#
# All facts in this task follow the same pattern.
- name: Get the best postgresql packages value
  set_fact:
    _postgresql_packages: |-
      {%- if postgresql_packages is not none -%}
        {{ postgresql_packages }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_packages) and
           (ansible_distribution_major_version|string in __postgresql_packages[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_packages[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_packages) -%}
         {{ __postgresql_packages[ansible_distribution|lower]['_value'] }}
      {%- else %}
        {{ none }}
      {%- endif -%}

- name: Get the best data dir value
  set_fact:
    _postgresql_data_dir: |-
      {%- if postgresql_data_dir is not none -%}
        {{ postgresql_data_dir }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_data_dir) and
           (ansible_distribution_major_version|string in __postgresql_data_dir[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_data_dir[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_data_dir) -%}
         {{ __postgresql_data_dir[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}

- name: Get the best service name value
  set_fact:
    _postgresql_service_name: |-
      {%- if postgresql_service_name is not none -%}
        {{ postgresql_service_name }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_service_name) and
           (ansible_distribution_major_version|string in __postgresql_service_name[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_service_name[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_service_name) -%}
         {{ __postgresql_service_name[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}

- name: Get the best repo package value
  set_fact:
    _postgresql_repo_package: |-
      {%- if postgresql_official_rhel_repo_package is not none -%}
        {{ postgresql_official_rhel_repo_package }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_official_rhel_repo_package) and
           (ansible_distribution_major_version|string in __postgresql_official_rhel_repo_package[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_official_rhel_repo_package[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_official_rhel_repo_package) -%}
         {{ __postgresql_official_rhel_repo_package[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}

- name: Get the best repo value
  set_fact:
    _postgresql_official_debian_repo: |-
      {%- if postgresql_official_debian_repo is not none -%}
        {{ postgresql_official_debian_repo }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_official_debian_repo) and
           (ansible_distribution_major_version|string in __postgresql_official_debian_repo[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_official_debian_repo[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_official_debian_repo) -%}
         {{ __postgresql_official_debian_repo[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}

- name: Get the best conf filename value
  set_fact:
    _postgresql_conf_filename: |-
      {%- if postgresql_conf_filename is not none -%}
        {{ postgresql_conf_filename }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_conf_filename) and
           (ansible_distribution_major_version|string in __postgresql_conf_filename[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_conf_filename[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_official_rhel_repo_package) -%}
         {{ __postgresql_conf_filename[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}

- name: Get the best hba conf value
  set_fact:
    _postgresql_pg_hba_conf_filename: |-
      {%- if postgresql_pg_hba_conf_filename is not none -%}
        {{ postgresql_pg_hba_conf_filename }}
      {%- elif (
           (ansible_distribution|lower in __postgresql_pg_hba_conf_filename) and
           (ansible_distribution_major_version|string in __postgresql_pg_hba_conf_filename[ansible_distribution|lower])
         ) -%}
         {{ __postgresql_pg_hba_conf_filename[ansible_distribution|lower][ansible_distribution_major_version|string]['_value'] }}
      {%- elif (ansible_distribution|lower in __postgresql_pg_hba_conf_filename) -%}
         {{ __postgresql_pg_hba_conf_filename[ansible_distribution|lower]['_value'] }}
      {%- else -%}
        {{ none }}
      {%- endif -%}
