---
# handlers file for ansible-role-postgresql
- name: Reload postgres
  service:
    name: "{{ _postgresql_service_name }}"
    state: "{{ postgresql_service_reload_state }}"
  listen: reload postgres
  when:
    - "postgresql_service_state in ['started']"
