---
- name: Converge
  hosts: all
  tasks:
    - name: Set data dir fact
      set_fact:
        _data_dir: >-
          {%- if ansible_distribution == 'CentOS' -%}
            /var/lib/pgsql/11/data
          {%- elif ansible_distribution == 'Debian' -%}
            /var/lib/postgresql/11/main
          {%- else -%}
            {{ none }}
          {%- endif -%}

    - name: "Include ansible-role-postgresql"
      include_role:
        name: "ansible-role-postgresql"
      vars:
        postgresql_version: 11
        postgresql_no_log: false
        postgresql_users:
          - name: test
            password: abc123
            encrypted: true
            state: present
          - name: test1
            password: abc123
            encrypted: true
            expires: "2030-01-01"
            state: present

        postgresql_databases:
          - name: testdb
            template: template0
            owner: test
            state: present
          - name: testdb2
            owner: test1
            state: present

        postgresql_data_dir: "{{ _data_dir }}"
        postgresql_conf:
          data_directory: "{{ _data_dir }}"
