---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint .
platforms:
  - name: postgresql-molecule-centos-7-instance
    image: "centos:centos7"
    #    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
  - name: postgresql-molecule-centos-8-instance
    image: "centos:centos8"
    #    pre_build_image: true
    privileged: true
    tmpfs:
     - /run
     - /tmp
    volumes:
     - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: /usr/sbin/init
  - name: postgresql-molecule-debian-buster-instance
    image: python:3-buster
    #    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
  - name: postgresql-molecule-debian-stretch-instance
    image: python:3-stretch
#    pre_build_image: true
    privileged: true
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: postgresql-molecule-ubuntu-20-04-instance
#    image: ubuntu:20.04
#    pre_build_image: true
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#  - name: postgresql-molecule-ubuntu-20-10-instance
#    image: ubuntu:20.10
#    pre_build_image: true
#    tmpfs:
#      - /run
#      - /tmp
#    volumes:
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
  dockerfile: ../resources/playbooks/Dockerfile.j2
  playbooks:
    prepare: prepare.yml
#  inventory:
#    group_vars:
#      # setting for the platform instance named 'instance'
#      all:
#        ansible_user: ansible
verifier:
  name: testinfra
